# Generated by Django 2.0.5 on 2018-05-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Owners',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='images',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='species',
        ),
    ]
