# Generated by Django 2.0.5 on 2018-05-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0007_auto_20180531_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='plant',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='see_data.Plant'),
        ),
    ]
