# Generated by Django 2.0.5 on 2018-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0012_plant_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaves',
        ),
        migrations.AddField(
            model_name='plant',
            name='locX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='locY',
            field=models.IntegerField(default=0),
        ),
    ]
