# Generated by Django 2.0.5 on 2018-05-31 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0013_auto_20180531_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant234'),
        ),
    ]
