# Generated by Django 2.0.5 on 2018-05-31 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0016_auto_20180531_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
