# Generated by Django 2.0.5 on 2018-05-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0017_auto_20180531_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='age',
        ),
    ]
