# Generated by Django 2.0.5 on 2018-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0021_auto_20180531_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='optimal_heat',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='species',
            name='optimal_moist',
            field=models.IntegerField(default=60),
        ),
    ]
