# Generated by Django 2.0.5 on 2018-05-29 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=250)),
                ('instances', models.CharField(max_length=253)),
                ('images', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='see_data.Plants'),
        ),
    ]
