# Generated by Django 2.0.5 on 2018-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0003_auto_20180530_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='image',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='species',
        ),
    ]
