# Generated by Django 2.0.5 on 2018-05-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0006_auto_20180531_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='plant',
        ),
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='Alvin', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='instance',
            field=models.CharField(default='plant1', max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(default='Strawberry', max_length=50),
        ),
    ]
