# Generated by Django 2.0.5 on 2018-05-31 03:14

from django.db import migrations, models
import django.db.models.deletion
import see_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0010_remove_owner_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='instance',
        ),
    ]
