# Generated by Django 2.0.5 on 2018-05-31 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0014_auto_20180531_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(default='Strawberry', max_length=50)),
                ('optimal_light', models.IntegerField(default=6)),
                ('optimal_moisture', models.CharField(default='High', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='current_heat',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='plant',
            name='current_light',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='plant',
            name='current_moist',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='current_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='see_data.Owner'),
        ),
        migrations.AddField(
            model_name='plant',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 5, 27)),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='see_data.Species'),
        ),
    ]
