# Generated by Django 2.0.5 on 2018-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0018_remove_owner_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
