# Generated by Django 2.0.5 on 2018-05-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0019_owner_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='age',
        ),
    ]
