# Generated by Django 2.0.5 on 2018-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0020_remove_owner_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='optimal_moisture',
        ),
        migrations.AddField(
            model_name='species',
            name='optimal_moist',
            field=models.CharField(default='High', max_length=55),
        ),
        migrations.AlterField(
            model_name='species',
            name='optimal_light',
            field=models.IntegerField(default=65),
        ),
    ]
