# Generated by Django 2.0.5 on 2018-05-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_data', '0022_auto_20180531_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
